{"name": "Test login attempt with wrong credentials", "status": "passed", "parameters": [{"name": "login_data", "value": "('', '')"}], "start": 1537445384494, "stop": 1537445425919, "uuid": "39872a25-7d97-4bc4-a746-26f0320586bb", "historyId": "f4349e5ae2ba336cc5543edae9a81784", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data2]", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User management"}, {"name": "story", "value": "Login"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "14380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}