{"name": "Test login attempt with wrong credentials", "status": "passed", "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}], "start": 1537445430584, "stop": 1537445451682, "uuid": "5edf3d9a-6176-4889-a052-e8bea3df509c", "historyId": "384da9776e08e2dbe65b4e7101c5fe29", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data3]", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User management"}, {"name": "story", "value": "Login"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "14380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}