{"name": "Test login attempt with wrong credentials", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got an unexpected keyword argument 'type'", "trace": "self = <src.tests.test_selenium.TestLogin object at 0x000001CA11365208>\nlogin_data = ('', '')\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1f17b3bc12d48449d4435d7d069b3ebf\")>\n\n    @allure.step\n    @allure.tag('UI')\n    @allure.feature('User management')\n    @allure.story('Login')\n    @allure.title(\"Test login attempt with wrong credentials\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.parametrize(\"login_data\", [(\"alex_art\", \"test\"),\n                                            (\"alex_art\", \"\"),\n                                            (\"\", \"\"),\n                                            (\"Alexander_Artemov\", \"test\")])\n    def test_login_incorrect(self, login_data, driver):\n        login_page = LoginPage(driver)\n        login_page.go(\"http://jira.hillel.it:8080/\")\n        login_page.login(*login_data)\n    \n>       allure.attach('screenshot', driver.get_screenshot_as_png(), type=AttachmentType.PNG)\nE       TypeError: __call__() got an unexpected keyword argument 'type'\n\nsrc\\tests\\test_selenium.py:61: TypeError"}, "steps": [{"name": "test_login_incorrect", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got an unexpected keyword argument 'type'\n", "trace": "  File \"c:\\users\\aartemov\\pycharmprojects\\pythoncourse\\phase4\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 141, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\aartemov\\PycharmProjects\\pythoncourse\\phase5\\src\\tests\\test_selenium.py\", line 61, in test_login_incorrect\n    allure.attach('screenshot', driver.get_screenshot_as_png(), type=AttachmentType.PNG)\n"}, "parameters": [{"name": "login_data", "value": "('', '')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"1f17b3bc12d48449d4435d7d069b3ebf\")>"}], "start": 1537454343973, "stop": 1537454360047}], "parameters": [{"name": "login_data", "value": "('', '')"}], "start": 1537454343972, "stop": 1537454360048, "uuid": "a5fa5dfc-267d-47f9-bd75-95afb4ca4aac", "historyId": "f4349e5ae2ba336cc5543edae9a81784", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data2]", "labels": [{"name": "feature", "value": "User management"}, {"name": "tag", "value": "UI"}, {"name": "story", "value": "Login"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}